name: Java CI

on: [push]

permissions: read-all
jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21, 23, 24, 25]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn test jacoco:report --file pom.xml -B 

  build-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        java: [17, 21, 23, 24, 25]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn package --file pom.xml -B 

  build-macos:

    runs-on: macOS-latest
    strategy:
      matrix:
        java: [17, 21, 23, 24, 25]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn package --file pom.xml -B 

  build-sonar:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 77e7b80c7f497f0861daa958b9a4320894af0948
        run: mvn -B test jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=javadev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=javadev_underscore-java11

      - uses: codecov/codecov-action@v5
        with:
          files: target/site/jacoco/jacoco.xml
          name: codecov
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: 26562e18-0254-43a5-81a3-1eb721ea7e24
